import javax.swing.JOptionPane;
/**
 * This class represents the GUI interface for a cashier user menu.
 * It allows the user to:
 * - Clock In and Clock Out
 * - Reset their password
 * - Log out of the system
 * - Access customer info, sell tickets and concessions, and check out customers
 * @author Taryn Davis
 */
public class Cashier_Menu extends javax.swing.JFrame {
    private Cashier currentCashier;
    private InventoryManager inventoryManager;
    private ScheduleManager scheduleManager;
    private AppController controller = AppController.getInstance();
    

    /**
     * Creates new form Cashier_Menu
     */
    public Cashier_Menu(Cashier cashier, InventoryManager inventoryManager, ScheduleManager scheduleManager) {
        this.currentCashier = cashier;
        this.inventoryManager = inventoryManager;
        this.scheduleManager = scheduleManager;
        
        initComponents();
        lblCashierName.setText(cashier.getName());
        String lastStatus = ClockHandler.getLastClockStatus(currentCashier.getName());
        lblClockStatus.setText(lastStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panelCashier = new javax.swing.JTabbedPane();
        tabAccountMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCashierName = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClockIn = new javax.swing.JButton();
        btnClockOut = new javax.swing.JButton();
        lblClockStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabCustomerInfo = new javax.swing.JPanel();
        tabSellTicket = new javax.swing.JPanel();
        tabSellConcession = new javax.swing.JPanel();
        tabCheckout = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAccountMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome!");
        tabAccountMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        lblCashierName.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCashierName.setForeground(new java.awt.Color(255, 102, 255));
        lblCashierName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashierName.setText("Cashier Name");
        tabAccountMenu.add(lblCashierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 190, -1));

        btnResetPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnResetPassword.setText("Reset Password");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });
        tabAccountMenu.add(btnResetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 140, -1));

        btnLogout.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        tabAccountMenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, -1));

        jPanel1.setBackground(new java.awt.Color(194, 202, 202));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        btnClockIn.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnClockIn.setText("Clock In");
        btnClockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockInActionPerformed(evt);
            }
        });

        btnClockOut.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnClockOut.setText("Clock Out");
        btnClockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockOutActionPerformed(evt);
            }
        });

        lblClockStatus.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblClockStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClockStatus.setText("Clocked In/Out");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Current Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnClockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnClockOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClockStatus)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClockIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClockOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClockStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabAccountMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 240, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("______________");
        tabAccountMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI BACKGROUND.png"))); // NOI18N
        tabAccountMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 870, 510));

        panelCashier.addTab("Account Menu", tabAccountMenu);

        javax.swing.GroupLayout tabCustomerInfoLayout = new javax.swing.GroupLayout(tabCustomerInfo);
        tabCustomerInfo.setLayout(tabCustomerInfoLayout);
        tabCustomerInfoLayout.setHorizontalGroup(
            tabCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        tabCustomerInfoLayout.setVerticalGroup(
            tabCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        panelCashier.addTab("Customer Info", tabCustomerInfo);

        javax.swing.GroupLayout tabSellTicketLayout = new javax.swing.GroupLayout(tabSellTicket);
        tabSellTicket.setLayout(tabSellTicketLayout);
        tabSellTicketLayout.setHorizontalGroup(
            tabSellTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        tabSellTicketLayout.setVerticalGroup(
            tabSellTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        panelCashier.addTab("Sell Ticket", tabSellTicket);

        javax.swing.GroupLayout tabSellConcessionLayout = new javax.swing.GroupLayout(tabSellConcession);
        tabSellConcession.setLayout(tabSellConcessionLayout);
        tabSellConcessionLayout.setHorizontalGroup(
            tabSellConcessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        tabSellConcessionLayout.setVerticalGroup(
            tabSellConcessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        panelCashier.addTab("Sell Concession", tabSellConcession);

        javax.swing.GroupLayout tabCheckoutLayout = new javax.swing.GroupLayout(tabCheckout);
        tabCheckout.setLayout(tabCheckoutLayout);
        tabCheckoutLayout.setHorizontalGroup(
            tabCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        tabCheckoutLayout.setVerticalGroup(
            tabCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        panelCashier.addTab("Checkout", tabCheckout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        controller.saveAllData();
        new Login_Application().setVisible(true);
        this.dispose();
          
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnClockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockInActionPerformed
        ClockHandler.clockAction(currentCashier.getName(), currentCashier.getRole(), "Clock In");
        lblClockStatus.setText("Clocked In");
        JOptionPane.showMessageDialog(null, "Clocked In!");
    }//GEN-LAST:event_btnClockInActionPerformed

    private void btnClockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockOutActionPerformed
        ClockHandler.clockAction(currentCashier.getName(), currentCashier.getRole(), "Clock Out");
        lblClockStatus.setText("Clocked Out");
        JOptionPane.showMessageDialog(null, "Clocked Out!");
    }//GEN-LAST:event_btnClockOutActionPerformed

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        String newPass = JOptionPane.showInputDialog(this, "Enter new Password:");
        if (newPass == null || newPass.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Passowrd not changed.");
            return;
        }
        currentCashier.getCredential().updatePassword(newPass);
        JOptionPane.showMessageDialog(this, "Password Updated!");
         
    }//GEN-LAST:event_btnResetPasswordActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClockIn;
    private javax.swing.JButton btnClockOut;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCashierName;
    private javax.swing.JLabel lblClockStatus;
    private javax.swing.JTabbedPane panelCashier;
    private javax.swing.JPanel tabAccountMenu;
    private javax.swing.JPanel tabCheckout;
    private javax.swing.JPanel tabCustomerInfo;
    private javax.swing.JPanel tabSellConcession;
    private javax.swing.JPanel tabSellTicket;
    // End of variables declaration//GEN-END:variables
}
