import javax.swing.JOptionPane;
/**
 *
 * @author Taryn
 */
public class Cashier_Menu extends javax.swing.JFrame {
    private Cashier currentCashier;
    private InventoryManager inventoryManager;
    private ScheduleManager scheduleManager;
    private AppController controller = AppController.getInstance();
    

    /**
     * Creates new form Cashier_Menu
     */
    public Cashier_Menu(Cashier cashier, InventoryManager inventoryManager, ScheduleManager scheduleManager) {
        this.currentCashier = cashier;
        this.inventoryManager = inventoryManager;
        this.scheduleManager = scheduleManager;
        
        initComponents();
        lblCashierName.setText(cashier.getName());
        String lastStatus = ClockHandler.getLastClockStatus(currentCashier.getName());
        lblClockStatus.setText(lastStatus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        panelCashier = new javax.swing.JTabbedPane();
        tabAccountMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCashierName = new javax.swing.JLabel();
        btnClockOut = new javax.swing.JButton();
        btnClockIn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblClockStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tabCustomerInfo = new javax.swing.JPanel();
        tabSellTicket = new javax.swing.JPanel();
        tabSellConcession = new javax.swing.JPanel();
        tabCheckout = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAccountMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Welcome!");
        tabAccountMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        lblCashierName.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCashierName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCashierName.setText("Cashier Name");
        tabAccountMenu.add(lblCashierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 190, -1));

        btnClockOut.setText("Clock Out");
        btnClockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockOutActionPerformed(evt);
            }
        });
        tabAccountMenu.add(btnClockOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 90, 30));

        btnClockIn.setText("Clock In");
        btnClockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClockInActionPerformed(evt);
            }
        });
        tabAccountMenu.add(btnClockIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Current Status:");
        tabAccountMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        lblClockStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblClockStatus.setText("Clocked In/Out");
        tabAccountMenu.add(lblClockStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jButton1.setText("Reset Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tabAccountMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        tabAccountMenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        panelCashier.addTab("Account Menu", tabAccountMenu);

        javax.swing.GroupLayout tabCustomerInfoLayout = new javax.swing.GroupLayout(tabCustomerInfo);
        tabCustomerInfo.setLayout(tabCustomerInfoLayout);
        tabCustomerInfoLayout.setHorizontalGroup(
            tabCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        tabCustomerInfoLayout.setVerticalGroup(
            tabCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        panelCashier.addTab("Customer Info", tabCustomerInfo);

        javax.swing.GroupLayout tabSellTicketLayout = new javax.swing.GroupLayout(tabSellTicket);
        tabSellTicket.setLayout(tabSellTicketLayout);
        tabSellTicketLayout.setHorizontalGroup(
            tabSellTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        tabSellTicketLayout.setVerticalGroup(
            tabSellTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        panelCashier.addTab("Sell Ticket", tabSellTicket);

        javax.swing.GroupLayout tabSellConcessionLayout = new javax.swing.GroupLayout(tabSellConcession);
        tabSellConcession.setLayout(tabSellConcessionLayout);
        tabSellConcessionLayout.setHorizontalGroup(
            tabSellConcessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        tabSellConcessionLayout.setVerticalGroup(
            tabSellConcessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        panelCashier.addTab("Sell Concession", tabSellConcession);

        javax.swing.GroupLayout tabCheckoutLayout = new javax.swing.GroupLayout(tabCheckout);
        tabCheckout.setLayout(tabCheckoutLayout);
        tabCheckoutLayout.setHorizontalGroup(
            tabCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        tabCheckoutLayout.setVerticalGroup(
            tabCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        panelCashier.addTab("Checkout", tabCheckout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCashier)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCashier)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        controller.saveAllData();
        new Login_Application().setVisible(true);
        this.dispose();
          
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnClockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockInActionPerformed
        ClockHandler.clockAction(currentCashier.getName(), currentCashier.getRole(), "Clock In");
        lblClockStatus.setText("Clocked In");
        JOptionPane.showMessageDialog(null, "Clocked In!");
    }//GEN-LAST:event_btnClockInActionPerformed

    private void btnClockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClockOutActionPerformed
        ClockHandler.clockAction(currentCashier.getName(), currentCashier.getRole(), "Clock Out");
        lblClockStatus.setText("Clocked Out");
        JOptionPane.showMessageDialog(null, "Clocked Out!");
    }//GEN-LAST:event_btnClockOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String newPass = JOptionPane.showInputDialog(this, "Enter new Password:");
        if (newPass == null || newPass.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Passowrd not changed.");
            return;
        }
        currentCashier.getCredential().updatePassword(newPass);
        JOptionPane.showMessageDialog(this, "Password Updated!");
         
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClockIn;
    private javax.swing.JButton btnClockOut;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCashierName;
    private javax.swing.JLabel lblClockStatus;
    private javax.swing.JTabbedPane panelCashier;
    private javax.swing.JPanel tabAccountMenu;
    private javax.swing.JPanel tabCheckout;
    private javax.swing.JPanel tabCustomerInfo;
    private javax.swing.JPanel tabSellConcession;
    private javax.swing.JPanel tabSellTicket;
    // End of variables declaration//GEN-END:variables
}
