/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;


/**
 *
 * @author Taryn
 */
public class Login_Application extends javax.swing.JFrame {        
    
        //  Cashier 
        Credential cashierCred1 = new Credential("Mic.Car", "Treehouse2");
        Cashier cashier1 = new Cashier("Michael Carter", 28, 1003, 3, "Cashier", cashierCred1, 101);        
        Credential cashierCred2 = new Credential("Emm.Ree", "Sunflower45");
        Cashier cashier2 = new Cashier("Emma Reese", 25, 1004, 4, "Cashier", cashierCred2, 102);
        
        Credential cashierCred3 = new Credential("Rya.Jac", "BlueSky12");
        Cashier cashier3 = new Cashier("Ryan Jacobs", 18, 1005, 5, "Cashier", cashierCred3, 103);

        // Manager Users
        Credential managerCred1 = new Credential("Lil.Ben", "PastelDream9");
        Manager manager1 = new Manager("Lily Bennett", 40, 1001, 1, "Manager", managerCred1);
        
        Credential managerCred2 = new Credential("Jas.Wel", "Shadow99");
        Manager manager2 = new Manager("Jason Wells", 39, 1002, 2, "Manager", managerCred2);
         // Engineers
        Credential engineerCred1 = new Credential("Dan.Fos", "Mountain44");
        Engineer engineer1 = new Engineer("Daniel Foster", 34, 1006, 6, "Engineer", engineerCred1);
        
        Credential engineerCred2 = new Credential("Sar.Col", "CoffeeTime8");
        Engineer engineer2 = new Engineer("Sarah Collins", 33, 1007, 7, "Engineer", engineerCred2);

    /**
     * Creates new form Login_Application
     */
    public Login_Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        blogin = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jcshow_password = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Welcome!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Username");

        blogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        blogin.setText("Login");
        blogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });

        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Please enter your log-in details below");

        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });

        jcshow_password.setText("Show Password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcshow_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtuser)
                            .addComponent(jLabel1)
                            .addComponent(jpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcshow_password)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(blogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jcshow_password)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bexit)
                    .addComponent(blogin))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        blogin.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        // TODO add your handling code here:        
        String inputUser = jtuser.getText();
        String inputPass = new String(jpassword.getPassword());
        StaffManager staffManager = new StaffManager();        

        // Add all staff
        staffManager.addStaff(cashier1);
        staffManager.addStaff(cashier2);
        staffManager.addStaff(cashier3);

        staffManager.addStaff(manager1);
        staffManager.addStaff(manager2);

        staffManager.addStaff(engineer1);
        staffManager.addStaff(engineer2);
        
        
        if (jtuser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out username");
        }
        else if(jpassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out password");
        }
        else {
            boolean loggedIn = false;
            
            if (cashierCred1.getUsername().equals(inputUser) && cashierCred1.getPasswordHash().equals(inputPass)) {
                // open Cashier tab for cashier1
                JOptionPane.showMessageDialog(null, "Logged in as: " + cashier1.getName());
                // TODO: openCashierDashboard(cashier1);
                loggedIn = true;
            } else if (cashierCred2.getUsername().equals(inputUser) && cashierCred2.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + cashier2.getName());
                loggedIn = true;
            } else if (cashierCred3.getUsername().equals(inputUser) && cashierCred3.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + cashier3.getName());
                loggedIn = true;
            }

            // Check Managers
            else if (managerCred1.getUsername().equals(inputUser) && managerCred1.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + manager1.getName());
                ScheduleManager scheduleManager = new ScheduleManager();
                Manager_Menu menu = new Manager_Menu(manager1, staffManager, scheduleManager);
                menu.setVisible(true);
                this.dispose();
                loggedIn = true;
            } else if (managerCred2.getUsername().equals(inputUser) && managerCred2.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + manager2.getName());
                ScheduleManager scheduleManager = new ScheduleManager();
                Manager_Menu menu = new Manager_Menu(manager2, staffManager, scheduleManager);
                menu.setVisible(true);
                this.dispose();
                loggedIn = true;
            }

            // Check Engineers
            else if (engineerCred1.getUsername().equals(inputUser) && engineerCred1.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + engineer1.getName());
                loggedIn = true;
            } else if (engineerCred2.getUsername().equals(inputUser) && engineerCred2.getPasswordHash().equals(inputPass)) {
                JOptionPane.showMessageDialog(null, "Logged in as: " + engineer2.getName());
                loggedIn = true;
            }

            // If no match was found
            if (!loggedIn) {
                JOptionPane.showMessageDialog(null, "Wrong username or password!", "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bloginActionPerformed

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcshow_passwordActionPerformed
        if (jcshow_password.isSelected()) {
            jpassword.setEchoChar((char)0);
        }
        else {
            jpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jcshow_passwordActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton blogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox jcshow_password;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;
    // End of variables declaration//GEN-END:variables
}
