/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Taryn
 */
import javax.swing.JOptionPane;

public class Manager_Menu extends javax.swing.JFrame {

    private Manager currentManager;
    private StaffManager staffManager;
    
    /**
     * Creates new form Manager_Menu
     */
    public Manager_Menu(Manager manager, StaffManager staffManagerParam) {
        initComponents();
        this.currentManager = manager;        
        this.staffManager = staffManagerParam;
        
        lblManagerName.setText(manager.getName());         
   
        loadStaffTable();
        
    }
    
    private void loadStaffTable() {
        String[] columns = {"Name", "Age", "Staff ID", "Role"};
        
        java.util.List<Staff> staffList = staffManager.getAllStaff();
        String[][] data = new String[staffList.size()][4];
        
        for (int i = 0; i < staffList.size(); i++) {
            Staff s = staffList.get(i);
            data[i][0] = s.getName();
            data[i][1] = String.valueOf(s.getAge());
            data[i][2] = String.valueOf(s.getStaffID());
            data[i][3] = s.getRole();
        }
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columns);
        tblStaff.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jOptionPane1 = new javax.swing.JOptionPane();
        lblManagerName1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabAccountPane = new javax.swing.JTabbedPane();
        jAccountPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblManagerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnChangePassword = new javax.swing.JButton();
        jStaffPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        btnAddStaffMember = new javax.swing.JButton();
        btnRemoveStaffMember = new javax.swing.JButton();
        btnChangeStaffRole = new javax.swing.JButton();
        btnViewMoreDetails = new javax.swing.JButton();
        panelCustomerMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelMaintenanceMenu = new javax.swing.JPanel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        lblManagerName1.setText("Manager Name");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAccountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(3, 4, 94));
        lblWelcome.setText("Welcome!");
        jAccountPanel.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lblManagerName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblManagerName.setText("Manager Name");
        jAccountPanel.add(lblManagerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("__________");
        jAccountPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, 90));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jAccountPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Taryn\\Pictures\\Screenshots\\Screenshot 2025-04-30 230942.png")); // NOI18N
        jAccountPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        btnChangePassword.setText("Reset Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        jAccountPanel.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 30));

        tabAccountPane.addTab("Account Menu", jAccountPanel);

        jStaffPanel.setLayout(null);

        jLabel1.setText("Name:");
        jStaffPanel.add(jLabel1);
        jLabel1.setBounds(20, 30, 37, 16);

        jLabel5.setText("Age:");
        jStaffPanel.add(jLabel5);
        jLabel5.setBounds(20, 90, 37, 16);

        jLabel6.setText("ID:");
        jStaffPanel.add(jLabel6);
        jLabel6.setBounds(20, 150, 60, 16);

        jLabel7.setText("Role: ");
        jStaffPanel.add(jLabel7);
        jLabel7.setBounds(20, 210, 120, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Staff");
        jStaffPanel.add(jLabel8);
        jLabel8.setBounds(430, 10, 60, 60);

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStaff);

        jStaffPanel.add(jScrollPane1);
        jScrollPane1.setBounds(220, 60, 480, 170);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jStaffPanel.add(txtName);
        txtName.setBounds(20, 50, 180, 30);
        jStaffPanel.add(txtAge);
        txtAge.setBounds(20, 110, 180, 30);
        jStaffPanel.add(txtID);
        txtID.setBounds(20, 170, 180, 30);
        jStaffPanel.add(txtRole);
        txtRole.setBounds(20, 230, 180, 30);

        btnAddStaffMember.setText("Add Staff Member");
        btnAddStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffMemberActionPerformed(evt);
            }
        });
        jStaffPanel.add(btnAddStaffMember);
        btnAddStaffMember.setBounds(20, 280, 180, 23);

        btnRemoveStaffMember.setText("Remove Staff Member");
        btnRemoveStaffMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStaffMemberActionPerformed(evt);
            }
        });
        jStaffPanel.add(btnRemoveStaffMember);
        btnRemoveStaffMember.setBounds(520, 260, 180, 23);

        btnChangeStaffRole.setText("Change Staff Role");
        btnChangeStaffRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStaffRoleActionPerformed(evt);
            }
        });
        jStaffPanel.add(btnChangeStaffRole);
        btnChangeStaffRole.setBounds(520, 300, 180, 23);

        btnViewMoreDetails.setText("View More Details");
        btnViewMoreDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMoreDetailsActionPerformed(evt);
            }
        });
        jStaffPanel.add(btnViewMoreDetails);
        btnViewMoreDetails.setBounds(520, 340, 180, 23);

        tabAccountPane.addTab("Staff Menu", jStaffPanel);

        panelCustomerMenu.setLayout(null);
        tabAccountPane.addTab("Customer Menu", panelCustomerMenu);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabAccountPane.addTab("Movie Menu", jPanel4);

        javax.swing.GroupLayout panelMaintenanceMenuLayout = new javax.swing.GroupLayout(panelMaintenanceMenu);
        panelMaintenanceMenu.setLayout(panelMaintenanceMenuLayout);
        panelMaintenanceMenuLayout.setHorizontalGroup(
            panelMaintenanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        panelMaintenanceMenuLayout.setVerticalGroup(
            panelMaintenanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        tabAccountPane.addTab("Maintenance Menu", panelMaintenanceMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAccountPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabAccountPane, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMoreDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMoreDetailsActionPerformed
        int selectedRow = tblStaff.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a staff member.");
            return;
        }
        
        int id = Integer.parseInt(tblStaff.getValueAt(selectedRow, 2).toString());
        Staff s = staffManager.getStaffByID(id);
        if (s != null) {
            String details = "Name: " + s.getName()
                    + "\nAge: " + s.getAge()
                    + "\nID: " + s.getStaffID()
                    + "\nRole: " + s.getRole()
                    + "\nUsername: " + s.getCredential().getUsername()
                    + "\nPassword: " + s.getCredential().getPasswordHash();
            JOptionPane.showMessageDialog(this, details, "Staff Details", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnViewMoreDetailsActionPerformed

    private void btnAddStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffMemberActionPerformed
        String name = txtName.getText();
        String ageStr = txtAge.getText();
        String idStr = txtID.getText();
        String role = txtRole.getText();
        
        if (name.isEmpty() || ageStr.isEmpty() || idStr.isEmpty() || role.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }
        
        try {
            int age = Integer.parseInt(ageStr);
            int id = Integer.parseInt(idStr);
            
            String normalizedRole = role.toLowerCase();
            if (!normalizedRole.equals("cashier") && !normalizedRole.equals("manager") && !normalizedRole.equals("engineer")) {
                JOptionPane.showMessageDialog(this, "Role must be either: Cashier, Manager or Engineer");
                return;
            }
            
            for (Staff s : staffManager.getAllStaff()) {
                if (s.getStaffID() == id) {
                    JOptionPane.showMessageDialog(this, "Staff ID already exists.");
                    return;
                }
                if (s.getName().equalsIgnoreCase(name)) {
                    JOptionPane.showMessageDialog(this, "Staff name already exists.");
                    return;
                }
            }
            
            String username = JOptionPane.showInputDialog(this, "Create Username");
            String password = JOptionPane.showInputDialog(this, "Create Password");
            if (username == null || password == null) return;
            
            for (Staff s: staffManager.getAllStaff()) {
                if (s.getCredential().getUsername().equalsIgnoreCase(username)) {
                    JOptionPane.showMessageDialog(this, "Username already exists. Choose another.");
                    return;
                }
            }
            
            Credential cred = new Credential(username, password);
            Staff newStaff = new Staff(name, age, id, id, role, cred);
            staffManager.addStaff(newStaff);
            loadStaffTable();
            
            txtName.setText("");
            txtAge.setText("");
            txtID.setText("");
            txtRole.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age and ID must be numbers");
        }
    }//GEN-LAST:event_btnAddStaffMemberActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new Login_Application().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRemoveStaffMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStaffMemberActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStaff.getSelectedRow();
        if  (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a Staff Member to Remove");
            return;
        }
        
        String staffIDStr = tblStaff.getValueAt(selectedRow, 2).toString();
        String name = tblStaff.getValueAt(selectedRow, 0).toString(); 
        String idStr = tblStaff.getValueAt(selectedRow, 2).toString();
        
        int staffID = Integer.parseInt(staffIDStr);
        
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove \"" + name + "\"?", "Confirm Removal", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean removed = staffManager.removeStaffByID(staffID);
            if (removed) {
                loadStaffTable();
                JOptionPane.showMessageDialog(this, "Staff member removed");
            } else {
                JOptionPane.showMessageDialog(this, "Staff not found");
            }
        }
    }//GEN-LAST:event_btnRemoveStaffMemberActionPerformed

    private void btnChangeStaffRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStaffRoleActionPerformed
        int selectedRow = tblStaff.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a staff member.");
            return;
        }
        
        String idStr = tblStaff.getValueAt(selectedRow, 2).toString();
        int id = Integer.parseInt(idStr);
        Staff staff = staffManager.getStaffByID(id);
        
        if (staff != null) {
            String newRole = txtRole.getText();
            if (newRole.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter a new role.");
                return;
            }
            
            staff.setRole(newRole);
            loadStaffTable();
            JOptionPane.showMessageDialog(this, "Role Updated.");
        } else {
            JOptionPane.showMessageDialog(this, "Staff not found.");
        }
    }//GEN-LAST:event_btnChangeStaffRoleActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        String newPass = JOptionPane.showInputDialog(this, "Enter new Password:");
        if (newPass == null || newPass.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Passowrd not changed.");
            return;
        }
        currentManager.getCredential().updatePassword(newPass);
        JOptionPane.showMessageDialog(this, "Password Updated!");
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Manager_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Manager_Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStaffMember;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeStaffRole;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveStaffMember;
    private javax.swing.JButton btnViewMoreDetails;
    private javax.swing.JPanel jAccountPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jStaffPanel;
    private javax.swing.JLabel lblManagerName;
    private javax.swing.JLabel lblManagerName1;
    private javax.swing.JLabel lblWelcome;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JPanel panelCustomerMenu;
    private javax.swing.JPanel panelMaintenanceMenu;
    private javax.swing.JTabbedPane tabAccountPane;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
